import type React from "react";

const exportBtnBase = {
  display: "flex",
  alignItems: "center",
  gap: 5,
  padding: "4px 10px",
  background: "none",
  border: "1px solid var(--control-active-fg)",
  borderRadius: 5,
  fontSize: 12,
  color: "var(--control-active-fg)",
  flexShrink: 0,
} as const;

export const terminal = {
  runHeader: {
    padding: "16px 20px 8px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  runMetaRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    color: "var(--text-muted)",
    minWidth: 0,
    overflow: "hidden",
  },
  runMetaFixed: {
    flexShrink: 0,
  },
  runMetaBranchInline: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
    overflow: "hidden",
  },
  runMetaBranchText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  runMetricsRow: {
    marginTop: 8,
    display: "flex",
    gap: 12,
    flexWrap: "wrap" as const,
  },
  runMetricPill: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 8px",
    borderRadius: 6,
    background: "var(--bg-input)",
    border: "1px solid var(--border-dim)",
  },
  runMetricPillButton: {
    font: "inherit",
    cursor: "pointer",
  },
  runMetricPillLabel: {
    fontSize: 10,
    color: "var(--text-hint)",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: 0.4,
  },
  runMetricPillValue: {
    fontSize: 11,
    color: "var(--text-primary)",
    fontWeight: 600,
  },
  runSessionFilePillWrap: {
    position: "relative" as const,
    display: "inline-flex",
    alignItems: "center",
  },
  runSessionStatusDot: {
    display: "inline-block",
    position: "static" as const,
    bottom: "auto",
    right: "auto",
    flexShrink: 0,
  },
  runSessionCopyTooltip: {
    position: "absolute" as const,
    left: "50%",
    bottom: "calc(100% + 6px)",
    transform: "translateX(-50%)",
    zIndex: 20,
    padding: "5px 8px",
    borderRadius: 6,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.18)",
    color: "var(--text-secondary)",
    fontSize: 11,
    fontWeight: 600,
    lineHeight: 1.4,
    whiteSpace: "nowrap" as const,
    pointerEvents: "none" as const,
  },
  cancelBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid var(--border-medium)",
    borderRadius: 5,
    fontSize: 12,
    color: "var(--text-muted)",
    cursor: "pointer",
    flexShrink: 0,
  },
  exportBtn: { ...exportBtnBase, cursor: "pointer" as const },
  exportBtnBusy: { ...exportBtnBase, cursor: "not-allowed" as const, opacity: 0.6 },
  resumeBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid var(--control-active-fg)",
    borderRadius: 5,
    fontSize: 12,
    color: "var(--control-active-fg)",
    cursor: "pointer",
    flexShrink: 0,
  },
  doneBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid rgba(46, 160, 67, 0.35)",
    borderRadius: 5,
    fontSize: 12,
    color: "var(--success)",
    cursor: "pointer",
    flexShrink: 0,
  },
  terminalContainer: { flex: 1, overflow: "hidden" as const, padding: "10px 0 10px 10px" },
  shellTerminalPanel: {
    flexShrink: 0,
    borderTop: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column" as const,
  },
  shellTerminalResizeHandle: {
    height: 4,
    flexShrink: 0,
    cursor: "row-resize",
    background: "transparent",
  },
  shellTerminalHeader: {
    height: 32,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    padding: "0 10px 0 14px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
    gap: 8,
  },
  shellTerminalTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-primary)",
    flexShrink: 0,
  },
  shellTerminalTabs: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 4,
    overflowX: "auto" as const,
    overflowY: "hidden" as const,
  },
  shellTerminalTab: {
    height: 24,
    minWidth: 76,
    maxWidth: 112,
    padding: "0 5px 0 7px",
    borderRadius: 5,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 5,
    flex: "0 1 112px",
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-secondary)",
    boxShadow: "none",
  },
  shellTerminalTabIcon: {
    flexShrink: 0,
    color: "var(--text-hint)",
  },
  shellTerminalTabLabel: {
    flex: 1,
    minWidth: 0,
    fontSize: 11.5,
    fontWeight: 500,
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  shellTerminalTabClose: {
    background: "none",
    border: "none",
    color: "var(--text-hint)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 1,
    borderRadius: 4,
    cursor: "pointer",
    flexShrink: 0,
  },
  shellTerminalTabAdd: {
    width: 24,
    height: 24,
    borderRadius: 5,
    border: "none",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  shellTerminalCount: {
    fontSize: 11,
    color: "var(--text-muted)",
  },
  shellTerminalCloseButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 3,
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    color: "var(--text-hint)",
  },
  shellTerminalBody: {
    flex: 1,
    display: "flex",
    minHeight: 0,
  },
  shellTerminalViewport: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    position: "relative" as const,
  },
  interruptedSessionWrap: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    background: "var(--bg-root)",
  },
  interruptedBanner: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: 7,
    minHeight: 38,
    padding: "4px 28px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-root)",
  },
  interruptedBannerIcon: {
    width: 18,
    height: 18,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--warning)",
    flexShrink: 0,
  },
  interruptedBannerBody: {
    minWidth: 0,
    flex: "1 1 180px",
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  interruptedBannerTitle: {
    fontSize: 12.5,
    fontWeight: 650,
    color: "var(--text-primary)",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  interruptedBannerText: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  interruptedBannerActions: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap" as const,
    gap: 5,
    flexShrink: 0,
  },
  interruptedNoSessionPane: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 32px",
    color: "var(--text-hint)",
    fontSize: 13,
    lineHeight: 1.6,
    textAlign: "center" as const,
  },
  interruptedPrimaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 5,
    border: "1px solid var(--border-dim)",
    color: "var(--text-primary)",
    background: "var(--bg-card)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
  interruptedSecondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 5,
    border: "1px solid rgba(46, 160, 67, 0.24)",
    color: "var(--success)",
    background: "rgba(46, 160, 67, 0.055)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
  interruptedDangerBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 5,
    border: "1px solid rgba(248, 81, 73, 0.24)",
    color: "var(--danger)",
    background: "rgba(248, 81, 73, 0.055)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
} satisfies Record<string, React.CSSProperties>;
